// Listas fijas copiadas literalmente del <select> de index.html
// (~1039-1124): 24 idiomas, 52 provincias/países. El orden es el mismo que
// en el original (Español primero, el resto alfabético; provincias en
// orden alfabético con Ceuta/Melilla al final).
export const IDIOMAS = [
  "Español",
  "Alemán",
  "Búlgaro",
  "Checo",
  "Croata",
  "Danés",
  "Eslovaco",
  "Esloveno",
  "Estonio",
  "Finlandés",
  "Francés",
  "Griego",
  "Holandés",
  "Húngaro",
  "Inglés",
  "Italiano",
  "Letón",
  "Lituano",
  "Macedonio",
  "Polaco",
  "Portugués",
  "Rumano",
  "Ruso",
  "Ucraniano",
] as const;

export const PROVINCIAS = [
  "Álava",
  "Albacete",
  "Alicante",
  "Almería",
  "Asturias",
  "Ávila",
  "Badajoz",
  "Barcelona",
  "Burgos",
  "Cáceres",
  "Cádiz",
  "Cantabria",
  "Castellón",
  "Ciudad Real",
  "Córdoba",
  "Cuenca",
  "Gerona",
  "Granada",
  "Guadalajara",
  "Guipúzcoa",
  "Huelva",
  "Huesca",
  "Islas Baleares",
  "Jaén",
  "La Coruña",
  "La Rioja",
  "Las Palmas",
  "León",
  "Lérida",
  "Lugo",
  "Madrid",
  "Málaga",
  "Murcia",
  "Navarra",
  "Orense",
  "Palencia",
  "Pontevedra",
  "Salamanca",
  "Santa Cruz de Tenerife",
  "Segovia",
  "Sevilla",
  "Soria",
  "Tarragona",
  "Teruel",
  "Toledo",
  "Valencia",
  "Valladolid",
  "Vizcaya",
  "Zamora",
  "Zaragoza",
  "Ceuta",
  "Melilla",
] as const;

// Réplica de onCanalChange() (~2643-2658): qué roles son asignables a cada
// canal.
export const ROLES_POR_CANAL: Record<"nacional" | "exportacion", string[]> = {
  nacional: ["comercial_nacional", "responsable_nacional"],
  exportacion: ["comercial_exportacion", "responsable_exportacion"],
};
